version: '3.5'

services:
  db: 
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=postgres
    # TODO: figure out how to start the container with existing data
    # volumes:
    #   - ./postgres_db:/var/lib/postgresql/data
    networks:
      - transcendence

  backend: 
    build: 
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports: 
    # port for api
      - '3001:3000'
    # port for prisma
      - '5555:5555'
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - transcendence
    
  frontend:
    depends_on:
      - backend
    build: 
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
    # port for website
      - '3000:3000'
    volumes:
      - ./app:/app
    networks:
      - transcendence

networks:
  transcendence:
